// Mocks generated by Mockito 5.4.4 from annotations
// in youapp/test/blocs/profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:youapp/services/you_app_api/profile_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApi extends _i1.Mock implements _i2.ProfileApi {
  MockProfileApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Response?> createProfile(
    String? token,
    Map<String, dynamic>? profileData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [
            token,
            profileData,
          ],
        ),
        returnValue: _i3.Future<_i4.Response?>.value(),
      ) as _i3.Future<_i4.Response?>);

  @override
  _i3.Future<_i4.Response?> getProfile(String? token) => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [token],
        ),
        returnValue: _i3.Future<_i4.Response?>.value(),
      ) as _i3.Future<_i4.Response?>);

  @override
  _i3.Future<_i4.Response?> updateProfile({
    required String? token,
    String? name = r'',
    String? birthday = r'',
    int? height = -1,
    int? weight = -1,
    List<String>? interests = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #token: token,
            #name: name,
            #birthday: birthday,
            #height: height,
            #weight: weight,
            #interests: interests,
          },
        ),
        returnValue: _i3.Future<_i4.Response?>.value(),
      ) as _i3.Future<_i4.Response?>);
}
